name: pre-commit
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  autofix:
    description: 'Autofix files and commit changes.'
    required: false
    default: "false"
runs:
  using: composite
  steps:
  - uses: actions/setup-python@v3
    id: setup-python
    with:
      cache: 'pip'

  - run: python -m pip install pre-commit
    shell: bash
    if: steps.setup-python.outputs.cache-hit != "true"

  - uses: actions/cache@v3
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

  - run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    shell: bash

  - run: |
      date > generated.txt
      git config user.name github-actions
      git config user.email github-actions@github.com
      git add .
      git commit -m "generated"
      git push
    if: inputs.autofix == true
    shell: bash
