name: pre-commit
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  autofix:
    description: 'Autofix files and commit changes.'
    required: false
    default: "false"
runs:
  using: composite
  steps:

  - uses: actions/setup-python@v3
    id: setup-python

  - uses: actions/cache@v3
    id: cache_pip
    with:
      path: ~/.venv
      key: pre-commit|${{ steps.setup-python.outputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}

  - run: | 
      python -m venv ~/.venv
      source .venv/bin/activate
      python -m pip install pre-commit
    shell: bash
    if: steps.cache_pip.outputs.cache-hit != true

  - uses: actions/cache@v3
    with:
      path: ~/.cache/pre-commit
      key: pre-commit|${{ steps.setup-python.outputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}

  - run: | 
      source .venv/bin/activate
      pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    shell: bash

  - run: |
      date > generated.txt
      git config user.name github-actions
      git config user.email github-actions@github.com
      git add .
      git commit -m "generated"
      git push
    if: inputs.autofix == true
    shell: bash
