on:
  workflow_dispatch:
  pull_request:
  # push:
  #   branches: [main, test-me-*]

# permissions:
#   checks: write
#   contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-python@v3
    - name: self test action
      uses: ./
